Models/ChangePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CarRentalApp.Models
{
    public class ChangePasswordViewModel
    {
        public string? UserId { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current Password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at most {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New Password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm New Password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

}

Controllers/UserUtilsController.cs
using CarRentalApp.Data;
using CarRentalApp.Models;
using CarRentalApp.Models.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging;

namespace CarRentalApp.Controllers
{
    public class UserUtilsController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly AppDbContext _context;

        public UserUtilsController(AppDbContext context, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    var user = await _userManager.FindByEmailAsync(model.Email);
                    await UpdateIsRegular(user.Id);
                    await UpdateIsActive(user.Id, DateTime.Today.AddDays(-90));

                    await _userManager.UpdateAsync(user);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }
        public async Task<IActionResult> UpdateIsRegular(string userId, int rentalCountThreshold = 5)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            var rentalCount = await _context.RentalHistories
                                            .CountAsync(r => r.UserID == userId);

            user.IsRegular = rentalCount >= rentalCountThreshold;
            if (user.IsRegular)
            {
                user.Discount = 10;
            }
            await _userManager.UpdateAsync(user);

            return Ok();
        }

        public async Task<IActionResult> UpdateIsActive(string userId, DateTime lastRentedDateThreshold)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            user.IsActive = await _context.RentalHistories
                                         .AnyAsync(r => r.UserID == userId && r.RentalDate >= lastRentedDateThreshold);

            await _userManager.UpdateAsync(user);

            return Ok();
        }



        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ProfileUpdate(string id)
        {
            var user = await _context.Users.FindAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            var viewModel = new UserProfileModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                PhoneNumber = user.PhoneNumber,
            };

            return View(viewModel);
        }


        [HttpPost]
        [CustomAuthorize(Roles = "Admin,Staff,Customer")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ProfileUpdate(string id, UserProfileModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var user = await _context.Users
                    .FirstOrDefaultAsync(d => d.Id == id);

            if (user == null)
            {
                return NotFound();
            }


            user.FirstName = viewModel.FirstName;
            user.LastName = viewModel.LastName;
            user.PhoneNumber = viewModel.PhoneNumber;

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        [HttpGet]
        [CustomAuthorize(Roles = "Admin,Staff,Customer")]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [CustomAuthorize(Roles = "Admin,Staff,Customer")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);

                if (user == null)
                {
                    return NotFound();
                }

                var result = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);

                if (result.Succeeded)
                {
                    await _signInManager.RefreshSignInAsync(user);
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(model);
        }


    }
}

Views/UserUtils/ChangePassword.cshtml
@{
    ViewData["Title"] = "Change Password";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model ChangePasswordViewModel

<h2>Change Password</h2>
@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <h4>Please correct the following errors:</h4>
        <ul class="list-unstyled">
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}
<form asp-controller="UserUtils" asp-action="ChangePassword" method="post">
    <div class="form-group">
        <label for="OldPassword">Current Password</label>
        <input type="password" class="form-control" id="OldPassword" name="OldPassword" required>
    </div>
    <div class="form-group">
        <label for="NewPassword">New Password</label>
        <input type="password" class="form-control" id="NewPassword" name="NewPassword" required>
    </div>
    <div class="form-group">
        <label for="ConfirmPassword">Confirm Password</label>
        <input type="password" class="form-control" id="ConfirmPassword" name="ConfirmPassword" required>
    </div>
    <br/>
    <button type="submit" class="btn login-btn">Change Password</button>
</form>

Views/UserUtils/Index.cshtml
@using CarRentalApp.Models.Identity;
@using Microsoft.AspNetCore.Identity;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userName = User.Identity.Name;
    var userManager = Context.RequestServices.GetService<UserManager<AppUser>>();
    var user = await userManager.FindByNameAsync(userName);
    var isCustomer = await userManager.IsInRoleAsync(user, "Customer");
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h4>User Profile</h4>
                    <div class="d-flex my-2 justify-content-end">
                        <a asp-action="ProfileUpdate" class="btn login-btn me-2 float-end" asp-route-id="@user.Id">Edit</a>
                        @if ((@user.CitizenshipURL == null || @user.DrivingLicenseURL == null) && isCustomer)
                        {
                            <a class="btn login-btn float-end" href="@Url.Action("AddImages", "Customer")">Add Images</a>

                        }
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <label for="inputFirstName" class="col-sm-4 col-form-label">First Name:</label>
                        <div class="col-sm-8">
                            <p class="form-control-plaintext" id="inputFirstName">@user.FirstName</p>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputLastName" class="col-sm-4 col-form-label">Last Name:</label>
                        <div class="col-sm-8">
                            <p class="form-control-plaintext" id="inputLastName">@user.LastName</p>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputUsername" class="col-sm-4 col-form-label">Username:</label>
                        <div class="col-sm-8">
                            <p class="form-control-plaintext" id="inputUsername">@user.UserName</p>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputPhoneNumber" class="col-sm-4 col-form-label">Phone Number:</label>
                        <div class="col-sm-8">
                            <p class="form-control-plaintext" id="inputPhoneNumber">@user.PhoneNumber</p>
                        </div>
                    </div>
                    @if (isCustomer)
                    {
                        <div class="form-group row mb-3">
                            <label for="inputDrivingLicense" class="col-sm-4 col-form-label">Driving License:</label>
                            <div class="col-sm-8">
                                @if (!string.IsNullOrEmpty(user.DrivingLicenseURL))
                                {
                                    <img src="@user.DrivingLicenseURL" alt="Driving License" style="max-width: 100%;">
                                }
                                else
                                {
                                    <p class="text-danger form-control-plaintext">Please upload your driving license before trying to rent a car.</p>
                                }
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <label for="inputCitizenship" class="col-sm-4 col-form-label">Citizenship:</label>
                            <div class="col-sm-8">
                                @if (!string.IsNullOrEmpty(user.CitizenshipURL))
                                {
                                    <img src="@user.CitizenshipURL" alt="Citizenship" style="max-width: 100%;">
                                }
                                else
                                {
                                    <p class="text-danger form-control-plaintext">Please upload your citizenship before trying to rent a car.</p>
                                }
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

Views/UserUtils/ProfileUpdate.cshtml
@model CarRentalApp.Models.UserProfileModel

@{
    ViewData["Title"] = "ProfileUpdate";
}

<h1>Profile Update</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ProfileUpdate">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" type="tel" class="form-control"/>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save Changes" class="btn login-btn" />
                <a asp-action="Index" type="reset" class="btn btn-default">Cancel</a>
            </div>
        </form>
    </div>
</div>