Models/RentalRequest.cs
using CarRentalApp.Models.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarRentalApp.Models
{
    public class RentalRequest
    {
        [Key] public int ReqID { get; set; }
        [ForeignKey("Id")] public string UserID { get; set; }
        [ForeignKey("CarID")] public int? CarID { get; set; }
        public DateTime RequestDate { get; set; }
        public RentalRequestStatus Status { get; set; }
        [ForeignKey("Id")] public string? AuthorizedBy { get; set; }
        public virtual AppUser User { get; set; }
        public virtual Car Car { get; set; }
        public virtual AppUser AuthorizedByUser { get; set; }

        // Navigation property
        public virtual ICollection<RentalHistory> RentalHistories { get; set; }
        public virtual ICollection<Damage> Damages { get; set; }
    }
}

Controllers/RentalRequestController.cs
using CarRentalApp.Data;
using CarRentalApp.Models;
using CarRentalApp.Models.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace CarRentalApp.Controllers
{
    public class RentalRequestController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly IEmailSender _emailSender;

        public RentalRequestController(AppDbContext context, UserManager<AppUser> userManager, IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _emailSender = emailSender;
        }

        [HttpGet]
        [CustomAuthorize(Roles = "Customer,Admin,Staff")]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var userType = await _userManager.GetRolesAsync(user);

            List<RentalRequest> rentalRequests = new List<RentalRequest>();

            if (userType.Contains("Admin") || userType.Contains("Staff"))
            {
                rentalRequests = await _context.RentalRequests
                    .Include(r => r.User)
                    .Include(r => r.Car)
                    .ToListAsync();
            }
            else if (userType.Contains("Customer"))
            {
                rentalRequests = await _context.RentalRequests
                    .Include(r => r.User)
                    .Include(r => r.Car)
                    .Where(r => r.User.Id == user.Id)
                    .ToListAsync();
            }

            ViewData["UserType"] = userType.FirstOrDefault();

            return View(rentalRequests);
        }

        [CustomAuthorize(Roles = "Customer")]
        public async Task<IActionResult> Create(int carId)
        {
            if (ModelState.IsValid)
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                var rentalRequest = new RentalRequest
                {
                    CarID = carId,
                    UserID = userId,
                    RequestDate = DateTime.Now,
                    Status = RentalRequestStatus.Pending
                };

                _context.RentalRequests.Add(rentalRequest);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View();
        }

        [CustomAuthorize(Roles = "Admin,Staff")]
        public async Task<IActionResult> Approve(int id)
        {

            var rentalRequest = await _context.RentalRequests
                .Include(r => r.Car)
                .FirstOrDefaultAsync(r => r.ReqID == id);

            if (rentalRequest == null)
            {
                return NotFound();
            }

            rentalRequest.Status = RentalRequestStatus.Approved;

            var authUser = await _userManager.GetUserAsync(User);
            var userId = authUser?.Id;
            var authorizedUser = await _userManager.FindByIdAsync(userId);
            if (authorizedUser == null)
            {
                return NotFound();
            }


            var rentalHistory = new RentalHistory
            {
                CarID = (int)rentalRequest.CarID,
                UserID = rentalRequest.UserID,
                AuthorizedByID = userId,
                RentalDate = rentalRequest.RequestDate,
                TotalCost = rentalRequest.Car.RentalRate,
                RentalRequest = rentalRequest
            };
            rentalRequest.Car.IsAvailable = false;
            rentalRequest.AuthorizedBy = userId;
            _context.RentalHistories.Add(rentalHistory);
            await _context.SaveChangesAsync();

            var user = await _userManager.FindByIdAsync(rentalRequest.UserID);
            var emailSubject = "Rental Request Approved";
            var emailMessage = $"Dear {user.FirstName},<br><br>Your rental request for {rentalRequest.Car.Manufacturer} {rentalRequest.Car.Model} has been approved. Please proceed to the rental office to complete the necessary formalities.<br><br>Thank you,<br>Hamro Car Rental Team";
            await _emailSender.SendEmailAsync(user.Email, emailSubject, emailMessage);

            return RedirectToAction(nameof(Index));
        }

        [CustomAuthorize(Roles = "Admin,Staff")]
        public async Task<IActionResult> Reject(int id)
        {
            var rentalRequest = await _context.RentalRequests
                .Include(rr => rr.Car)
                .FirstOrDefaultAsync(rr => rr.ReqID == id);
            if (rentalRequest == null)
            {
                return NotFound();
            }

            rentalRequest.Status = RentalRequestStatus.Rejected;
            _context.Update(rentalRequest);
            await _context.SaveChangesAsync();

            var user = await _userManager.FindByIdAsync(rentalRequest.UserID);
            if (user == null)
            {
                return NotFound();
            }
            if (rentalRequest.Car == null)
            {
                return NotFound();
            }
            var emailSubject = "Rental Request Rejected";
            var emailMessage = $"Dear {user.FirstName},<br><br>Your rental request for {rentalRequest.Car.Manufacturer} {rentalRequest.Car.Model} has been rejected. Please contact our customer service team for more information.<br><br>Thank you,<br>The Car Rental Team";
            await _emailSender.SendEmailAsync(user.Email, emailSubject, emailMessage);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Cancel(int id)
        {
            var rentalRequest = await _context.RentalRequests
                .Include(r => r.User)
                .Include(r => r.Car)
                .FirstOrDefaultAsync(r => r.ReqID == id &&
                                           (r.Status == RentalRequestStatus.Pending ||
                                            r.Status == RentalRequestStatus.Approved));


            if (rentalRequest == null)
            {
                return NotFound();
            }
            rentalRequest.Car.IsAvailable = true;
            rentalRequest.Status = RentalRequestStatus.Canceled;
            _context.RentalRequests.Update(rentalRequest);
            await _context.SaveChangesAsync();


            return RedirectToAction("Index");
        }
    }
}

Views/RentalRequest/Index.cshtml
@model List<CarRentalApp.Models.RentalRequest>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="my-3 text-center text-white" style="background-color: teal; padding: 1rem;">Rental Requests</h1>
<div class="row mb-5">
    @if (ViewData["UserType"]?.ToString() == "Customer")
    {
        <table id="cusRequestTable">
            <thead>
                <tr>
                    <th>Request ID</th>
                    <th>Car</th>
                    <th>Request Date</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var rentalRequest in Model)
                {
                    <tr>
                        <td>@rentalRequest.ReqID</td>
                        <td>@rentalRequest.Car.Manufacturer @rentalRequest.Car.Model</td>
                        <td>@rentalRequest.RequestDate</td>
                        <td>@rentalRequest.Status</td>
                        <td>
                            @if (rentalRequest.Status == RentalRequestStatus.Approved)
                            {
                                <a href="@Url.Action("Create", "Damage", new { carId = rentalRequest.CarID, reqId = rentalRequest.ReqID, userId = rentalRequest.UserID })" class="btn btn-primary">Report Damage</a>
                            }
                            @if (rentalRequest.Status == RentalRequestStatus.Pending || rentalRequest.Status == RentalRequestStatus.Approved)
                            {
                                <a href="@Url.Action("Cancel", "RentalRequest", new { id = rentalRequest.ReqID })" class="btn btn-primary">Cancel Request</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    }
    else if (ViewData["UserType"]?.ToString() == "Admin" || ViewData["UserType"]?.ToString() == "Staff")
    {
        <table id="staffRequestTable">
            <thead>
                <tr>
                    <th>Request ID</th>
                    <th>Car</th>
                    <th>User</th>
                    <th>Request Date</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var rentalRequest in Model)
                {
                    <tr>
                        <td>@rentalRequest.ReqID</td>
                        <td>@rentalRequest.Car.Manufacturer @rentalRequest.Car.Model</td>
                        <td>@rentalRequest.User.FirstName @rentalRequest.User.LastName</td>
                        <td>@rentalRequest.RequestDate</td>
                        <td>@rentalRequest.Status</td>
                        <td>
                            @if (rentalRequest.Status == RentalRequestStatus.Pending && rentalRequest.Status != RentalRequestStatus.Canceled)
                            {
                                <a href="@Url.Action("Approve", "RentalRequest", new { id = rentalRequest.ReqID })" class="btn btn-success">Approve</a>
                                <a href="@Url.Action("Reject", "RentalRequest", new { id = rentalRequest.ReqID })" class="btn btn-danger">Reject</a>
                            }
                            @if (rentalRequest.Status == RentalRequestStatus.Approved)
                            {
                                <a href="@Url.Action("Return", "RentalHistory", new { id = rentalRequest.ReqID })" class="btn btn-primary">Record Payment</a>


                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    }
</div>